services:
  postgres:
    image: postgres:15.4
    container_name: banking-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: localdevpassword
    ports:
      - "5432:5432"
    volumes:
      - banking_postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: banking-kafka-local
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - banking_kafka_data:/var/lib/kafka/data

  redis:
    image: redis:7
    container_name: banking-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  banking_postgres_data:
  banking_kafka_data:
