apiVersion: v1
kind: Secret
metadata:
  name: banking-db-secret
  namespace: banking-app
type: Opaque
data:
  DB_USERNAME: ZGJhZG1pbg==
  DB_PASSWORD: eW91ci1zZWN1cmUtcGFzc3dvcmQ=
  JWT_SECRET_KEY: ZjcwNGRjNjRhOTlkNjFhY2JhOGY3OWE1M2QzY2IyNmU3OTAzZThhZTdhYWU4YjFhODQyMWE2YTdkNTM2Mzk3ZQ==
  KYC_WEBHOOK_SECRET: Zjg4YTBlMzZmZjdiOTdlMGExZTgyNzExMGE3OTFlYTE5MjMyNjcyMDY0YmUxYjdhY2IxMTY5M2FkOTg5YWM2Mg==
