# this yaml file is for microservice auth service (01-auth-service)

# auth service deployment this will be the workload

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
        # this is a place holder for now
        # I will replace 'your-docker-registry' with my actual Docker Hub username
        # I am more worried about building the file rn not actual values
          image: your-docker-registry/auth-service:latest
          ports:
            - containerPort: 8080
          # this is where we import the namespace configmap and the secret I just built
          envFrom:
            - configMapRef:
                name: banking-global-config
            - secretRef:
                name: banking-db-secret
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.banking-app.svc.cluster.local:9092"
---
# this is the internal balancer aka the auth service network router
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: banking-app
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8080
      targetPort: 8080
