apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: your-docker-registry/transaction-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: banking-global-config
            - secretRef:
                name: banking-db-secret
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.banking-app.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking-app
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - port: 8080
      targetPort: 8080