spring:
  application:
    name: 02-profile-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: dbadmin
    password: localdevpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
